Project setup
cgomezb/protractor-workshop-2017 pull request #1
Opened 2017-10-04 23:26 UTC by cgomezb

2017-10-04 23:59 UTC, aperdomob requested changes

2017-10-04 23:59 UTC, aperdomob commented on LICENSE
> +Copyright (c) 2017 www.psl.com.co
En este archivo va tu nombre

2017-10-04 23:59 UTC, aperdomob commented on package.json
> +}
EOF

2017-10-05 14:23 UTC, cgomezb commented on package.json
> +}
Done

2017-10-05 14:49 UTC, aperdomob approved these changes

2017-10-05 15:19 UTC, merged